name: e2e test

on:
  push:
    branches:
      - e2e-test

jobs:
  main:
    name: e2e test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

    - name: install golang
      run: 
        sudo apt install golang

    - name: install e2e utils
      run: 
        sudo go get -u github.com/onsi/ginkgo/ginkgo
        sudo go get -u github.com/onsi/gomega/...
  
    - name: start test
      run:
        sudo make test-e2e-node PARALLELISM=1 FOCUS=Sysctls